### PR TITLE
Added a Chess AI + Game

### PR DESCRIPTION
**Pull request by nnisarggada**

### CODE REVIEW

**Comment by sree-hari-s** [comment]
The project seems to be nice but, there is an issue when there is a Stalemate the game doesn't show Draw,
Also, can you structure the assets of the game into another folder?
Include proper documentation on the Python topics used in the Game you have created in the Readme file instead of just Installation.

**Comment by nnisarggada** [comment]
> The project seems to be nice but, there is an issue when there is a Stalemate the game doesn't show Draw, Also, can you structure the assets of the game into another folder? Include proper documentation on the Python topics used in the Game you have created in the Readme file instead of just Installation.

Stalemate seems to be working (tests with https://www.chess.com/blog/JCH2021/the-fastest-stalemate-possible-in-chess). Other changes have been made.

**Comment by sree-hari-s** [comment]
> > The project seems to be nice but, there is an issue when there is a Stalemate the game doesn't show Draw, Also, can you structure the assets of the game into another folder? Include proper documentation on the Python topics used in the Game you have created in the Readme file instead of just Installation.
> 
> Stalemate seems to be working (tested with https://www.chess.com/blog/JCH2021/the-fastest-stalemate-possible-in-chess). Could you mention how to replicate the issue you faced? Other changes have been made.

When all pieces get eliminated. It should be draw due to insufficient pieces. But here we are still able to move both kings.

**Comment by nnisarggada** [comment]
Ah yes. This isn't stalement and other draw case (such as this one) haven't been accounted for as I simply don't know how to implement a good solution for them :P

Any ideas?

**Comment by sree-hari-s** [comment]
Oh my bad not stalemate but draw. I will have to look into it. Nice work by the way.

**Review by sree-hari-s — APPROVED** [review]

**Comment by nnisarggada** [comment]
> Oh my bad not stalemate but draw. I will have to look into it. Nice work by the way.

Thank you <3

If you do find a solution, lmk via contact@nnisarg.in or you could send a PR to github.com/nnisarggada/NyChess

Thank you for the merge :D

**Pull request merged**
