### PR TITLE
Add KbdXylo project

### PR DESCRIPTION
**Pull request by Zedeldi**
Add KbdXylo project - demonstrates library usage, threads, classes, and platform-dependent imports.

### CODE REVIEW

**Comment by sree-hari-s** [comment]
Nice work please change the name of the project also include a Readme.md file including a brief description on the project.

**Comment by Zedeldi** [comment]
Name changed to be clearer and README added.
Please let me know if you need anything else.

**Comment by sree-hari-s** [comment]
image
image

I am having some issue while installing the requirements can you guide me on solving this issue?

**Comment by Zedeldi** [comment]
Only the top two requirements are needed on Windows. On POSIX systems, the additional two GObject libraries are required for `boombox`.

**Comment by sree-hari-s** [comment]
> Only the top two requirements are needed on Windows. On POSIX systems, the additional two GObject libraries are required for `boombox`.

image

I am still having some issue

**Comment by Zedeldi** [comment]
Likely an issue with how `Boombox` is implemented in Windows, as this works in Linux-based systems. I can have a look later.

**Comment by Zedeldi** [comment]
On Windows, it will now set the `is_alias` flag of `winsound`, so that it does not try to verify the passed file location.
Please try again and let me know if the issue persists, thanks.

**Comment by sree-hari-s** [comment]
> On Windows, it will now set the `is_alias` flag of `winsound`, so that it does not try to verify the passed file location. Please try again and let me know if the issue persists, thanks.

image


now the program seem to work but this issue seem to exist

**Comment by Zedeldi** [comment]
`volume` is now passed to `play_tone` as a keyword-argument, which is ignored on Windows.
See [boombox](https://github.com/mixmastamyk/boombox/blob/master/boombox.py) for more information.

**Review by sree-hari-s — APPROVED** [review]

**Comment by sree-hari-s** [comment]
LGTM, really nice work, Leave a ⭐ and also contribute more fun projects like this.👌

**Pull request merged**
